### ISSUE TITLE
Clarify licensing

### ISSUE THREAD

**Issue by skobls** [skobls/arduscope#1]
When I was creating the repository, GitHub asked me if I want to put the project under any license.
My personal choice would be to use an open-source license, since we're not doing anything really novel here. But are there any restrictions from the side of the university?

**Comment by MateiVidican** [comment]
Normally it shouldn't be any problem, so open sources is ok.

**Comment by skobls** [comment]
Got reply from Thomas (the tutor). The university does not restrict us, moreover, Thomas would urge us to choose an open-source license. So I have chosen the MIT license.
